fix typos in docstrings
PrefectHQ/prefect-aws pull request #109
Opened 2022-09-16 14:06 UTC by discdiver

## Summary

Fixes a few typos in ECSTask docstring.

## Relevant Issue(s)

## Checklist
- [ x] Summarized PR's changes in the **Unreleased** section of the [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

2022-09-16 16:04 UTC, ahuang11 requested changes

2022-09-16 16:04 UTC, ahuang11 commented on CHANGELOG.md
> +Typos in ECSTask docstring.
Perhaps this doesn't need to be in CHANGELOG
```suggestion
```

2022-09-16 18:17 UTC, discdiver commented
lol. Agree. Maybe the PR template should specify the Changelog is optional
- now it wants a checkmark.


On Fri, Sep 16, 2022 at 12:04 PM Andrew ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In CHANGELOG.md
> <https://github.com/PrefectHQ/prefect-aws/pull/109#discussion_r973178777>:
>
> > @@ -16,6 +16,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
>
>  ### Removed
>
>
>
>  ### Fixed
>
> +Typos in ECSTask docstring.
>
>
> Perhaps this doesn't need to be in CHANGELOG
> ⬇️ Suggested change
>
> -Typos in ECSTask docstring.
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PrefectHQ/prefect-aws/pull/109#pullrequestreview-1110914174>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2Y3GMFPWSXSATAIGFMY7TV6SLCBANCNFSM6AAAAAAQOLU67E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-16 18:18 UTC, ahuang11 commented
I agree

2022-09-21 21:29 UTC, ahuang11 commented
Would you like me to wrap this up for you?

2022-09-21 21:55 UTC, discdiver commented
Thanks, Andrew. I didn't see you had made the change. I committed it.

2022-09-21 21:57 UTC, ahuang11 approved these changes

2022-09-21 22:00 UTC, merged