Read AWS Secrets with 'SecretString'
PrefectHQ/prefect-aws pull request #274
Opened 2023-06-07 17:19 UTC by nick-amplify

Closes https://github.com/PrefectHQ/prefect-aws/issues/265

### Example

### Screenshots

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

2023-06-07 17:28 UTC, desertaxle requested changes
Thanks for contributing @nick-amplify! Could you please add some tests covering this new functionality?

2023-06-07 17:28 UTC, desertaxle commented on CHANGELOG.md
> +* Added a check to AwsSecretsManager.load() for 'SecretString' as well as 'SecretBinary'
```suggestion
- Added a check to AwsSecretsManager.load() for 'SecretString' as well as 'SecretBinary' - [#274](https://github.com/PrefectHQ/prefect-aws/pull/274)
```

2023-08-07 17:36 UTC, desertaxle commented
@nick-amplify just checking to see if you can write some tests for this PR 🙂

2023-10-24 05:25 UTC, Bryan-Meier commented
I'm curious if this PR will make it into the main branch any time soon? We are wanting to leverage the SecretString functionality as all of our Secrets are in SecretString format and not SecretBinary. Thanks in advance!

2023-11-13 15:30 UTC, desertaxle approved these changes

2023-11-13 15:37 UTC, merged