Add default option for json dumps
PrefectHQ/prefect-aws pull request #294
Opened 2023-07-05 14:57 UTC by marianopenn

Closes #283.
Add default option for json dumps to avoid erroring on non-standard objects such as `datetime`. 

### Example

```
{
    "containerDefinitions": [
        {
            "cpu": 1024,
            "image": "prefecthq/prefect:2.1.0-python3.8",
            "memory": 2048,
            "name": "prefect"
        }
    ],
    "networkMode": "awsvpc",
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "4096",
    "memory": "16384",
    "registeredAt": "2023-06-29T18:55:42.764Z"
}
```

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

2023-07-05 19:17 UTC, bunchesofdonald requested changes
Hi @marianopenn, thank you so much for opening this PR! This looks great, except that it's missing some tests. Could you add at least one test?

2023-07-06 18:02 UTC, marianopenn commented
Hi @bunchesofdonald, would love to add a test! I'm having trouble mocking out the `describe_task_definition` call to return a `registeredAt` timestamp in `test_ecs_worker.py`. If I can get that to work, then running `test_task_definition_arn` with DEBUG logger enabled should test what we need here. 
Specifically, I'm trying to add a `"describe_task_definition"` section in `ecs_mocks` that can call out to a function like this:

```
def patch_describe_task_definition_with_registered_at(ecs_client, *args, **kwargs):
    # Patch describe_task_definition to return a registeredAt timestamp
    task_definition = ecs_client.describe_task_definition(
        taskDefinition=task["taskDefinitionArn"]
    )["taskDefinition"]
    task_definition = describe_task_definition(ecs_client, *args, **kwargs)
    task_definition["registeredAt"] = "2023-06-29T18:55:42.764Z"
    return task_definition
```
Is this the right way to go about this?
How can I make sure this gets injected in ecs_mock?

2023-07-07 15:52 UTC, bunchesofdonald commented
@marianopenn I'm not very familiar with this codebase, but that looks like a tricky place to try and mock. I'd probably look at updating `patch_describe_tasks_add_prefect_container` (you might also change the name of that function while you're there) to set `registeredAt` then you'd just need to have a test where the debugging is enabled to test this patch.

2023-07-10 21:30 UTC, marianopenn commented
@bunchesofdonald The bug is in the `ECSWorker` class, which I believe is not called from the `ECSTask` code. So I do think the test has to be in `test_ecs_worker` and it needs to mock the `describe_task_definition` method to return `registeredAt`. Still no luck on my end in adding the mock. I'm unable to modify the form of the taskDefinition in the response from `ecs_client.describe_task_definition` to include `registeredAt`. 
Note, I think the moto package should be returning this, since it's clearly in the [ECS response spec](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs/client/register_task_definition.html).

2023-07-17 12:47 UTC, marianopenn commented
#296 Addressed same issue, without any tests.. Closing this

2023-07-17 12:47 UTC, closed without merging