AWS S3 copy and move tasks and `S3Bucket` methods
PrefectHQ/prefect-aws pull request #316
Opened 2023-09-27 19:06 UTC by dominictarro

Added

- `prefect_aws.s3.s3_copy`
- `prefect_aws.s3.s3_move`
- `prefect_aws.s3.S3Bucket.copy_object`
- `prefect_aws.s3.S3Bucket.move_object`

Closes #315

### Example

```python
from prefect_aws.s3 import s3_copy, s3_move

@flow
async def test_flow():
    await s3_copy(
        source_path="object",
        source_bucket_name="my-bucket",
        target_path="my-bucket/object",
        target_bucket_name="my-backup-bucket",
        aws_credentials=aws_credentials,
        aws_client_parameters=client_parameters,
    )
    await s3_move(
        source_path="object",
        source_bucket_name="my-bucket",
        target_path="archive/object",
        aws_credentials=aws_credentials,
        aws_client_parameters=client_parameters,
    )
```

```python
from prefect_aws import S3Bucket

my_bucket = S3Bucket("my-bucket")
my_bucket.copy_object("critical/object", "my-bucket/object", target_bucket_name="my-backup-bucket")

my_bucket.move_object("object", "archive/object")
```

### Screenshots

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

2023-09-28 15:07 UTC, desertaxle requested changes
Thanks for the contribution! Let me know if you have any questions about any of my comments!

2023-09-28 15:07 UTC, desertaxle commented on prefect_aws/s3.py
> +    )
I'd recommend using `get_client` to ensure that the client parameters on `aws_credentials` are respected.

```suggestion
    s3_client = aws_credentials.get_client("s3")
```

2023-09-28 15:07 UTC, desertaxle commented on tests/test_s3.py
> +        client_parameters,
It looks like the `client_parameter` fixture isn't used in this test.

2023-09-28 15:07 UTC, desertaxle commented on tests/test_s3.py
> +        client_parameters,
It looks like the `client_parameter` fixture isn't used in this test. Can it be removed?

2023-09-28 15:07 UTC, desertaxle commented on tests/test_s3.py
> +        client_parameters,
It looks like the `client_parameter` fixture isn't used in this test. Can it be removed?

2023-09-28 18:27 UTC, dominictarro commented on prefect_aws/s3.py
> +        to copy objects within or between buckets.
Yeah so the `stream_from` is good when there isn't a single set of credentials that can read from the source and write to the destination. The destination I gave in #276 was with a public bucket like NOAA's GHCN-D bucket, which must be read via an unsigned request. Its shortcoming is that the object has to be downloaded to the Python process, then uploaded again. Sometimes that is necessary, but sometimes we can just use S3's internal copy operation, which completes large copies in seconds.

Will add context to the docstrings of both methods.

2023-09-28 19:29 UTC, dominictarro commented
@desertaxle 

- Added documentation to suggest when the native S3 operations should be used versus `S3Bucket.stream_from`.
- client credentials are no longer passed directly to `s3_copy` nor `s3_move`
- `s3_copy` and `s3_move` use `AwsCredentials.get_s3_client`
- `client_parameters` direct fixture removed from test functions

2023-10-06 15:23 UTC, desertaxle requested changes
Thanks for making the requested update @dominictarro! I left some comments on some fixtures that aren't being used, but once those are removed this PR is good to go!

2023-10-06 15:23 UTC, desertaxle commented on tests/test_s3.py
> +    @pytest.mark.parametrize("client_parameters", aws_clients[-1:], indirect=True)
This fixture is unused and can be removed.
```suggestion
```

2023-10-06 15:23 UTC, desertaxle commented on tests/test_s3.py
> +@pytest.mark.parametrize("client_parameters", aws_clients, indirect=True)
This fixture is unused and can be removed.
```suggestion
```

2023-10-09 04:10 UTC, dominictarro commented
The fixture is necessary for other fixtures. Removing it throws an error like so

```
/Users/dominictarro/Documents/GitHub/prefect-aws/tests/test_s3.py::test_s3_copy failed with error: Test failed with exception
request = <SubRequest 'client_parameters' for <Function test_s3_copy>>
    @pytest.fixture
    def client_parameters(request):
>       client_parameters = request.param
E       AttributeError: 'SubRequest' object has no attribute 'param'
tests/test_s3.py:41: AttributeError
```

2023-10-10 20:09 UTC, desertaxle commented
Ah, that's right. I forgot about the logic that populates `client_parameters`. This looks good to me then!

2023-10-10 20:09 UTC, desertaxle approved these changes

2023-10-10 20:09 UTC, merged