Improvement/error handling task creation
PrefectHQ/prefect-aws pull request #406
Opened 2024-04-02 15:54 UTC by jeanluciano

Introduces logic to catch failures from the run task response. It raises a `RuntimeError` when it finds the list of failures populated of if either `tasks` or `failures` which will help with the index errors that can come up.

Closes #282

### Example

### Screenshots

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.

2024-04-03 14:46 UTC, desertaxle requested changes

2024-04-04 14:12 UTC, jeanluciano commented on tests/workers/test_ecs_worker.py
> +    assert task_definition["family"] == family
This test is from me checking out main as I didn't write any test for this.

2024-04-11 14:05 UTC, desertaxle approved these changes
LGTM!

2024-04-11 14:10 UTC, merged

2024-04-14 14:42 UTC, MohammedSiddiqui commented
@jeanluciano thanks for taking care of this!
@desertaxle any idea when these changes can be available now in a new release?

2024-04-15 09:00 UTC, rmnvncnt commented
Thanks a lot for that one!